spring.application.name=road-rules-api

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/road_rules_api
spring.datasource.username=root
spring.datasource.password=toortoor
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
